version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
    file:
        class: logging.handlers.RotatingFileHandler
        filename: ".log/wizard.log"
        maxBytes: 5_000_000   # 5 MB
        backupCount: 3
        formatter: simple
        level: DEBUG

root:
    level: INFO
    handlers: [console, file]
